### ISSUE TITLE
Auto-lock app not working

### ISSUE THREAD

**Issue by jarun** [dessant/lock-threads-app#2]
I have been using the app in one of my projects and it's working as expected.

Around 4/5 days back I configured the app and added another project [nnn](https://github.com/jarun/nnn). However, none of the old issues or PRs have been locked so far. Can you please take a look if I'm missing something?

**Comment by dessant** [comment]
The hosted GitHub app instance intermittently shuts down because people select "all repositories" during installation and the app does not scale well at all. I have restarted the instance now, but it should not be relied upon.

I plan to shut down the app entirely in the next few months, so you should switch to https://github.com/dessant/lock-threads, which is more secure, uses GitHub actions, and shows none of the scaling issues this app has.

For example, your new action for [googler](https://github.com/jarun/googler/blob/master/.github/lock.yml) would look like this:

```yaml
name: 'Lock threads'

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v2
        with:
          github-token: ${{ github.token }}
          issue-lock-inactive-days: '60'
          issue-lock-reason: ''
          pr-lock-inactive-days: '60'
          pr-lock-reason: ''
```

The repo description has further examples, let me know if you need help with porting!

**Comment by jarun** [comment]
> I plan to shut down the app entirely in the next few months

I would request you not to do that. If someone (like me in this case) really wants the functionality to work (s)he will get back to you. IMO it's very easy to use and could still be available on request for people who are not abusing it.

**Comment by dessant** [comment]
GitHub actions are even easier to use and offer more control, you just have to commit a configuration file and you're done. I would rather not put considerable effort into maintaining an app and a server instance, unless there is a good reason for not wanting to use GitHub actions.

**Comment by jarun** [comment]
What would be the specific scope of the access token (github-token)?

Would just `repo` -> `public_repo` suffice?

**Comment by jarun** [comment]
If that's the wrong type of token, how to generate the github-token?

**Comment by dessant** [comment]
The token is populated by GitHub, there is no need to set it. You can find more details here: https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token

**Comment by dessant** [comment]
Here's an example of a working workflow file: https://github.com/dessant/lock-threads/blob/master/.github/workflows/lock.yml

The old app configuration should be removed when you set up the new action.

**Comment by jarun** [comment]
I have made these changes: https://github.com/jarun/nnn/commit/9b7b9d80be7f5372c810b8df5a6e4a52835499fd

and removed nnn from the auto-lock app config. Please confirm if that's enough.

**Comment by dessant** [comment]
Yes, your changes should work, the action will run once a day and lock 50 issues. If you have a large backlog of issues that have not been locked yet, you could temporarily increase the frequency of scheduled runs, and then switch it back after a week.

This schedule will run the job once an hour:
```yaml
on:
  schedule:
    - cron: '0 * * * *'
```
