### ISSUE TITLE
bot gone wild

### ISSUE THREAD

**Issue by steveoh** [dessant/lock-threads-app#3]
any idea why the bot is locking issues multiple times?

https://github.com/agrc/gis.utah.gov/pull/1351#issuecomment-649123100

**Comment by dessant** [comment]
Thanks for opening the issue! It looks like the app instance ran out of memory and that may have caused it to behave this way. I've temporarily shut down the app until I have time to block users that have installed the app for all repositories.

In any case, this app is on track to be deprecated, so you should migrate to the version built on GitHub actions.

https://github.com/dessant/lock-threads

Your current config would translate to this workflow file:

```yaml
name: 'Lock threads'

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v2
        with:
          github-token: ${{ github.token }}
          issue-lock-inactive-days: '91'
          issue-exclude-created-before: '2018-01-01'
          pr-lock-inactive-days: '91'
          pr-exclude-created-before: '2018-01-01'
```

Make sure to remove the old config and uninstall the legacy app after migrating.
